/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lc_les_LCGLRender */

#ifndef _Included_com_lc_les_LCGLRender
#define _Included_com_lc_les_LCGLRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lc_les_LCGLRender
 * Method:    ndkInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_les_LCGLRender_ndkInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_lc_les_LCGLRender
 * Method:    ndkPaintGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lc_les_LCGLRender_ndkPaintGL
  (JNIEnv *, jobject);

/*
 * Class:     com_lc_les_LCGLRender
 * Method:    ndkResizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lc_les_LCGLRender_ndkResizeGL
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
